export enum StorageEnum {
    // 系统设置
    STORAGE_SYSTEM_SETTING = 'STORAGE_SYSTEM_SETTING',
    // 当前主题
    STORAGE_DESIGN = 'STORAGE_DESIGN',
    // 用户信息
    STORAGE_USER_INFO = 'STORAGE_USER_INFO',

    // 配置路由
    STORAGE_ROUTES = 'STORAGE_ROUTES',

    // 图标Layout
    STORAGE_CHART_LAYOUT_STORE = 'STORAGE_CHART_LAYOUT_STORE',
}